Feature/popup
vegaitglobal/posao-sansi-website pull request #121
Opened 2023-10-17 12:05 UTC by nikolakokic95

Popup komponeneta trebace nam na vise razlictih strana. Primeniti na joboffers strani na buttone.

2023-10-17 15:34 UTC, roknicmilos requested changes

2023-10-17 15:34 UTC, roknicmilos commented on opportunity_job_app/src/components/Popup/Popup.tsx
> +    link_url: string;
Ovde bih koristio `camelCase` umesto `snake_case`.

2023-10-17 15:34 UTC, roknicmilos commented on opportunity_job_app/src/components/Popup/Popup.tsx
> +            if(elementsDetails.link_visibility) {setLinkVis('')} else {setLinkVis('popup__element-hide')}
Zbog preglednosti, podelio bih if/else u vise redova, npr:
```
if (elementsDetails.popup_visibility) {
    setDisp("popup--active")
}else { 
    setDisp("")
}
```

Ovo vazi i za ostale delove gde imamo blok koda obelezen viticastim zagradama: `useEffect` i `closePopup`

2023-10-17 15:34 UTC, roknicmilos commented on opportunity_job_app/src/components/Popup/Popup.tsx
> +export default Popup;
Kad sam vec ostavio neke komentare na ovaj PR, ostavljam ovde i manje bitan: single quotes -> double quotes :D

2023-10-18 06:18 UTC, nikolakokic95 commented on opportunity_job_app/src/components/Popup/Popup.tsx
> +export default Popup;
Pusovane su promene za PR

2023-10-18 07:20 UTC, roknicmilos approved these changes

2023-10-18 07:20 UTC, merged