Add popup for buttons
vegaitglobal/posao-sansi-website pull request #124
Opened 2023-10-18 12:12 UTC by nikolakokic95

2023-10-18 17:16 UTC, roknicmilos requested changes

2023-10-18 17:16 UTC, roknicmilos commented on opportunity_job_app/src/components/JobOfferDetails/JobOfferDetails.tsx
> +                    linkUrl: '/job-offers',
Vrednosti koje se ponavljaju bih izdvojio u poseban objekat i koristio bih ga i za success i za error popup:
```
const commonPupupDetails = {
    popupVisibility: true,
    paragraphSecondVisibility: true,
    linkVisibility: true,
    linkText: 'Nazad na poslove',
    linkUrl: '/job-offers',
}
```
Primer za success:
```
{
    paragraphFirstText: 'Vasa prijava je uspeno prosledjena!',
    paragraphSecondText: 'Uskoro ce Vam se javiti neko iz organizacije ATINA',
    ...commonPupupDetails
}
```

2023-10-18 17:16 UTC, roknicmilos commented on opportunity_job_app/src/components/JobOfferDetails/JobOfferDetails.tsx
> +                    paragraphSecondText: 'Please try again later',
Ovaj tekst bih napisao na srpskom kako bi bili konzistenti sa ostatkom teksta u kodu (koji je sav na srpskom), bez obzira sto ce se sve to premestati u JSON fajlove za prevode.

2023-10-18 17:16 UTC, roknicmilos commented on opportunity_job_app/src/components/JobOfferDetails/JobOfferDetails.tsx
> +                            <Popup elementsDetails={popupDetails} />
Da li je potrebno da se `<Popup elementsDetails={popupDetails} />` ponavlja?
Da li mozemo da ga stavimo usoid oba button-a, tj. izvan `{ jobOffer.has_enrolled ? ( ...` bloka?

2023-10-19 08:46 UTC, nikolakokic95 commented on opportunity_job_app/src/components/JobOfferDetails/JobOfferDetails.tsx
> +                            <Popup elementsDetails={popupDetails} />
Izbacio sam ga izvan sad je samo <Popup elementsDetails={popupDetails} />. Promene su pusovane.

2023-10-20 06:44 UTC, roknicmilos approved these changes

2023-10-20 06:44 UTC, merged